name: Matthew Holmes
favicon: null
layout_spectrum: 0.50327
typography_spectrum: 0.39498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ddcbc2'
    - '#9c7165'
    - '#bea398'
    - '#5e3746'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
